'''learn decorator'''
from datetime import datetime

def perf_logger(func):
    """Measure performance as a logger"""
    def wrapper():
        before_exec_time = datetime.now()
        func()
        after_exec_time = datetime.now()
        print(f"time taken to execute is {str(after_exec_time-before_exec_time)}")
    return wrapper


@perf_logger
def algorithm_measurement_method():
    """Create an algorithm to measure the performance with decorator"""
    int_list = []
    for item in range(0, 10000):
        item = item + 1
        int_list.append(item)
    print(f"list generated by this method{int_list}")

algorithm_measurement_method()
